version: "3"

services: 
  app-invite: 
    build: .
    command: php bin/console server:run 0.0.0.0
    ports: 
      - "8000:8000"
    volumes: 
      - .:/var/www/html/invite
    links: 
      - db-invite

  db-invite:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: senha-invite


